theme: jekyll-theme-chirpy
baseurl: ""
lang: en
timezone: Asia/Karachi

title: Muhammad Hamza
tagline: Aspiring Cybersecurity Enthusiast
description: >
  Technical blog by Muhammad Hamza covering Networking, Security, and IT topics.

url: "https://raohamzaanwar.github.io"

github:
  username: raohamzaanwar

social:
  name: Muhammad Hamza
  email: your-email@example.com
  links:
    - https://github.com/raohamzaanwar
    - https://www.linkedin.com/in/raohamzaanwar

theme_mode: light
avatar: /assets/img/personal/hamza.jpg
toc: true

comments:
  provider: none

paginate: 10
sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - node_modules
